package GUI;


import GUI.login;
import chainmanagement.Employee;
import chainmanagement.Message;
import chainmanagement.Product;
import chainmanagement.Store;
import chainmanagement.TimeDifference;
import java.awt.Color;
import java.awt.Component;
import static java.awt.event.MouseEvent.BUTTON1;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import org.jdesktop.swingx.border.DropShadowBorder;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACK
 */
public class supervisorPanel extends javax.swing.JFrame{

    /**
     * Creates new form supervisorPanel
     */
      ArrayList<Employee> send=new ArrayList<>();
      ArrayList<Message> messages=new ArrayList<>();
      ArrayList<Employee> myEmployees=new ArrayList<>();
      Product refprod=new Product();
      Product ad;
      Message ref=new Message();
      Message sen;
      ArrayList<Product> myProducts=new ArrayList<>();
      ArrayList<Product> all=new ArrayList<>();
      public Store infoStore ;
      Employee infoPerson;
      Employee firePerson;
      Timer timer1 = new Timer();
      Timer timer2 = new Timer();
      Timer timer3 = new Timer();
      Timer slideTimer1 = new Timer();
      Timer slideTimer2 = new Timer();
      
      
      boolean in;
      boolean clicked;
    
      
      boolean new_message;
      boolean inbox_bool;
      boolean chart_bool;
      boolean stock_bool;
      boolean worker_bool;
      boolean info_bool = true;
      
    public supervisorPanel(Employee e) {
      
        initComponents();
        infoPerson=e;
        svinbox.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable3.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        prodtable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        Store ref=new Store();
        infoStore=(Store)ref.get_item(infoPerson.getPlace());
        lineChart.id = e.getPlace();
        lineChart l = new lineChart(chart);
        
        //inbox_init();
        jLabel17.setVisible(false);
        jLabel39.setVisible(false);
        dispResult.setVisible(false);
        jLabel16.setVisible(false);
        pos_info.setForeground(new Color(255,204,51));
        setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShadowColor(Color.BLACK);
        shadow.setShowLeftShadow(true);
        shadow.setShowRightShadow(true);
        shadow.setShowBottomShadow(true);
        shadow.setShowTopShadow(true);
        shadow.setShadowSize(6);
        jPanel1.setBorder(shadow);
        messages=Message.getAll_Messages(infoPerson.getId());
        myEmployees=infoStore.getAllEmps();
        fireid.addItem("NONE");
        fillInfo();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jOptionPane1 = new javax.swing.JOptionPane();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JLabel();
        rightButton = new javax.swing.JLabel();
        pos_info = new javax.swing.JLabel();
        pos_worker = new javax.swing.JLabel();
        pos_stock = new javax.swing.JLabel();
        pos_chart = new javax.swing.JLabel();
        pos_inbox = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanelSlider1 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        info = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        svid = new javax.swing.JLabel();
        svname = new javax.swing.JLabel();
        svsname = new javax.swing.JLabel();
        svwplace = new javax.swing.JLabel();
        svstarting = new javax.swing.JLabel();
        svsalary = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        workerList = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        addWorker = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        addwsalary = new javax.swing.JTextField();
        addwsurname = new javax.swing.JTextField();
        addwname = new javax.swing.JTextField();
        addbuttonw = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        salarychange = new javax.swing.JTable();
        csalaryb = new javax.swing.JButton();
        dispResult = new javax.swing.JLabel();
        csalary = new javax.swing.JTextField();
        dispcs = new javax.swing.JLabel();
        deleteWorker = new javax.swing.JPanel();
        fireid = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        firecompens = new javax.swing.JLabel();
        firename = new javax.swing.JLabel();
        firesurname = new javax.swing.JLabel();
        firebutton = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        stock = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        prodtable = new javax.swing.JTable();
        prodBuy = new javax.swing.JButton();
        prodSell = new javax.swing.JButton();
        inbox = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        svinbox = new javax.swing.JTable();
        showMes = new javax.swing.JButton();
        sendMes = new javax.swing.JButton();
        chart = new javax.swing.JPanel();
        addProduct = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        prodd1 = new javax.swing.JLabel();
        prodbrand = new javax.swing.JTextField();
        prodcost = new javax.swing.JTextField();
        prodcat = new javax.swing.JComboBox<>();
        prodprice = new javax.swing.JTextField();
        prodtype = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        prodadd = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        prodd2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        prodstock = new javax.swing.JTextField();
        proddate = new javax.swing.JTextField();
        prodres = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        showMessage = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        messagecont = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fromLabel = new javax.swing.JLabel();
        subjectLabel = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        sendMessage = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sendCon = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sendSub = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addMessage = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        sendID = new javax.swing.JComboBox<>();
        showID = new javax.swing.JLabel();
        res = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Photo");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel8.setOpaque(true);

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(879, 802));

        jPanel2.setBackground(new java.awt.Color(66, 133, 245));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Chain Marketing Management System Supervisor Panel");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 17, 642, 54));

        LogoutButton.setBackground(new java.awt.Color(48, 117, 233));
        LogoutButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoutButton.setText("Logout");
        LogoutButton.setOpaque(true);
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogoutButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseReleased(evt);
            }
        });
        jPanel2.add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 93, 47));

        rightButton.setBackground(new java.awt.Color(48, 117, 233));
        rightButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rightButton.setForeground(new java.awt.Color(255, 255, 255));
        rightButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/right_arrow.png"))); // NOI18N
        rightButton.setOpaque(true);
        rightButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rightButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rightButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rightButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rightButtonMouseReleased(evt);
            }
        });
        jPanel2.add(rightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        pos_info.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pos_info.setForeground(new java.awt.Color(255, 255, 255));
        pos_info.setText("Info");
        jPanel2.add(pos_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        pos_worker.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pos_worker.setForeground(new java.awt.Color(255, 255, 255));
        pos_worker.setText("Worker list");
        jPanel2.add(pos_worker, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        pos_stock.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pos_stock.setForeground(new java.awt.Color(255, 255, 255));
        pos_stock.setText("Stock");
        jPanel2.add(pos_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        pos_chart.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pos_chart.setForeground(new java.awt.Color(255, 255, 255));
        pos_chart.setText("Chart");
        jPanel2.add(pos_chart, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        pos_inbox.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pos_inbox.setForeground(new java.awt.Color(255, 255, 255));
        pos_inbox.setText("Inbox");
        jPanel2.add(pos_inbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/warning.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/warning.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        jPanelSlider1.setBorder(null);
        jPanelSlider1.setPreferredSize(new java.awt.Dimension(879, 697));

        info.setBackground(new java.awt.Color(255, 255, 255));
        info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 133, 245), 10));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/81961.png"))); // NOI18N
        jLabel11.setText("Photo");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(48, 117, 233));
        jLabel12.setText("ID :");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(48, 117, 233));
        jLabel13.setText("Name :");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(48, 117, 233));
        jLabel14.setText("Work period :");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(48, 117, 233));
        jLabel15.setText("Salary :");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(48, 117, 233));
        jLabel18.setText("Place no :");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(48, 117, 233));
        jLabel19.setText("Surname :");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bluelogo.png"))); // NOI18N

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(47, 47, 47)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(svsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(svstarting, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(svsname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(svname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(svid, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(svwplace, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(378, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addContainerGap())
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoLayout.createSequentialGroup()
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(svid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(svname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(svsname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(svwplace, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(svstarting, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(svsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addContainerGap())
        );

        jPanelSlider1.add(info, "card3");

        workerList.setBackground(new java.awt.Color(255, 255, 255));
        workerList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 133, 245), 10));

        jTabbedPane2.setBackground(new java.awt.Color(66, 133, 245));
        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Surname"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable2);

        jTabbedPane2.addTab("On Work", jScrollPane4);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Surname", "Return Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable3);

        jTabbedPane2.addTab("On Vacation", jScrollPane5);

        addWorker.setBackground(new java.awt.Color(255, 255, 255));
        addWorker.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(48, 117, 233));
        jLabel28.setText("Surname :");
        addWorker.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(48, 117, 233));
        jLabel29.setText("Name :");
        addWorker.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(48, 117, 233));
        jLabel9.setText("Salary :");
        addWorker.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 60, -1));
        addWorker.add(addwsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 90, 30));
        addWorker.add(addwsurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 90, 30));
        addWorker.add(addwname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 90, 30));

        addbuttonw.setBackground(new java.awt.Color(48, 117, 233));
        addbuttonw.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addbuttonw.setForeground(new java.awt.Color(255, 255, 255));
        addbuttonw.setText("ADD");
        addbuttonw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonwActionPerformed(evt);
            }
        });
        addWorker.add(addbuttonw, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 180, 60));

        salarychange.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Surname", "Salary"
            }
        ));
        jScrollPane7.setViewportView(salarychange);

        addWorker.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 470, 350));

        csalaryb.setBackground(new java.awt.Color(48, 117, 233));
        csalaryb.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        csalaryb.setForeground(new java.awt.Color(255, 255, 255));
        csalaryb.setText("Change Salary");
        csalaryb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csalarybActionPerformed(evt);
            }
        });
        addWorker.add(csalaryb, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 120, -1));

        dispResult.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dispResult.setForeground(new java.awt.Color(48, 117, 233));
        addWorker.add(dispResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 180, 30));
        addWorker.add(csalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 110, 30));
        addWorker.add(dispcs, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 14, 190, 20));

        jTabbedPane2.addTab("Add Worker", addWorker);

        deleteWorker.setBackground(new java.awt.Color(255, 255, 255));
        deleteWorker.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fireid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireidActionPerformed(evt);
            }
        });
        deleteWorker.add(fireid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 131, -1));

        jLabel32.setText("Compensation :");
        deleteWorker.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 30));

        jLabel33.setText("ID :");
        deleteWorker.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 20));

        jLabel34.setText("Name :");
        deleteWorker.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 30));

        jLabel35.setText("Surname :");
        deleteWorker.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 30));

        firecompens.setText(" ");
        deleteWorker.add(firecompens, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 130, 30));

        firename.setText(" ");
        deleteWorker.add(firename, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 130, 30));

        firesurname.setText(" ");
        deleteWorker.add(firesurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 130, 30));

        firebutton.setBackground(new java.awt.Color(48, 117, 233));
        firebutton.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        firebutton.setForeground(new java.awt.Color(255, 255, 255));
        firebutton.setText("FIRE !!!");
        firebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firebuttonActionPerformed(evt);
            }
        });
        deleteWorker.add(firebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 240, 70));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(48, 117, 233));
        jLabel39.setText("The worker is a customer now");
        deleteWorker.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 260, 30));

        jTabbedPane2.addTab("Delete Worker", deleteWorker);

        javax.swing.GroupLayout workerListLayout = new javax.swing.GroupLayout(workerList);
        workerList.setLayout(workerListLayout);
        workerListLayout.setHorizontalGroup(
            workerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        workerListLayout.setVerticalGroup(
            workerListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jPanelSlider1.add(workerList, "card3");

        stock.setBackground(new java.awt.Color(255, 255, 255));
        stock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 133, 245), 10));

        prodtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Brand", "Type", "Cost", "Price", "Category", "Expire Date", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(prodtable);

        prodBuy.setText("BUY");
        prodBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodBuyActionPerformed(evt);
            }
        });

        prodSell.setText("SELL");
        prodSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodSellActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stockLayout = new javax.swing.GroupLayout(stock);
        stock.setLayout(stockLayout);
        stockLayout.setHorizontalGroup(
            stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
            .addGroup(stockLayout.createSequentialGroup()
                .addComponent(prodBuy, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodSell, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        stockLayout.setVerticalGroup(
            stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodSell, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanelSlider1.add(stock, "card3");

        inbox.setBackground(new java.awt.Color(255, 255, 255));
        inbox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 133, 245), 10));
        inbox.setPreferredSize(new java.awt.Dimension(879, 462));

        svinbox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "From", "Subject"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(svinbox);

        showMes.setText("Show Message");
        showMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMesActionPerformed(evt);
            }
        });

        sendMes.setText("Send Message");
        sendMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inboxLayout = new javax.swing.GroupLayout(inbox);
        inbox.setLayout(inboxLayout);
        inboxLayout.setHorizontalGroup(
            inboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(inboxLayout.createSequentialGroup()
                .addComponent(showMes, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sendMes, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        inboxLayout.setVerticalGroup(
            inboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inboxLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addGroup(inboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showMes, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(sendMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanelSlider1.add(inbox, "card2");

        chart.setBackground(new java.awt.Color(255, 255, 255));
        chart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 133, 245), 10));

        javax.swing.GroupLayout chartLayout = new javax.swing.GroupLayout(chart);
        chart.setLayout(chartLayout);
        chartLayout.setHorizontalGroup(
            chartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 919, Short.MAX_VALUE)
        );
        chartLayout.setVerticalGroup(
            chartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        jPanelSlider1.add(chart, "card3");

        addProduct.setBackground(new java.awt.Color(255, 255, 255));
        addProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 133, 245), 10));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(48, 117, 233));
        jLabel21.setText("Brand :");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(48, 117, 233));
        jLabel22.setText("Cost :");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(48, 117, 233));
        jLabel23.setText("Price :");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(48, 117, 233));
        jLabel24.setText("Type :");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(48, 117, 233));
        jLabel25.setText("Category :");

        prodd1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        prodd1.setForeground(new java.awt.Color(48, 117, 233));
        prodd1.setText("Expire Date :");

        prodcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodcostActionPerformed(evt);
            }
        });

        prodcat.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        prodcat.setForeground(new java.awt.Color(48, 117, 233));
        prodcat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FOOD", "OTHER" }));
        prodcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodcatActionPerformed(evt);
            }
        });

        prodprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodpriceActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(48, 117, 233));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Go Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        prodadd.setBackground(new java.awt.Color(48, 117, 233));
        prodadd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        prodadd.setForeground(new java.awt.Color(255, 255, 255));
        prodadd.setText("ADD");
        prodadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodaddActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(48, 117, 233));

        prodd2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        prodd2.setForeground(new java.awt.Color(48, 117, 233));
        prodd2.setText("YEAR-MONTH-DAY");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(48, 117, 233));
        jLabel26.setText("Amount:");

        proddate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proddateActionPerformed(evt);
            }
        });

        prodres.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        prodres.setForeground(new java.awt.Color(48, 117, 233));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bluelogo.png"))); // NOI18N

        javax.swing.GroupLayout addProductLayout = new javax.swing.GroupLayout(addProduct);
        addProduct.setLayout(addProductLayout);
        addProductLayout.setHorizontalGroup(
            addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProductLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addProductLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(27, 27, 27)
                        .addComponent(prodtype, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addProductLayout.createSequentialGroup()
                            .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22))
                            .addGap(21, 21, 21)
                            .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(prodbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(prodcost, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(addProductLayout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addGap(27, 27, 27)
                            .addComponent(prodprice, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addProductLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prodstock, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(108, 108, 108)
                .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addProductLayout.createSequentialGroup()
                        .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addProductLayout.createSequentialGroup()
                                .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prodadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(addProductLayout.createSequentialGroup()
                                        .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(prodd1)
                                            .addComponent(jLabel25))
                                        .addGap(18, 18, 18)
                                        .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(prodcat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(proddate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addProductLayout.createSequentialGroup()
                                        .addGap(0, 217, Short.MAX_VALUE)
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(addProductLayout.createSequentialGroup()
                                        .addComponent(prodd2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37))
                    .addGroup(addProductLayout.createSequentialGroup()
                        .addComponent(prodres, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addProductLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addContainerGap())
        );
        addProductLayout.setVerticalGroup(
            addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProductLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(prodcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8)
                    .addComponent(jLabel21)
                    .addComponent(prodbrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodd1)
                    .addComponent(jLabel22)
                    .addComponent(prodcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodd2)
                    .addComponent(proddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodadd)
                    .addComponent(jLabel23)
                    .addComponent(prodprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(addProductLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(prodres, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addProductLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(prodtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(prodstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addContainerGap())
        );

        jPanelSlider1.add(addProduct, "card3");

        showMessage.setBackground(new java.awt.Color(255, 255, 255));
        showMessage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 133, 245), 10));
        showMessage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        messagecont.setEditable(false);
        messagecont.setColumns(20);
        messagecont.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        messagecont.setRows(5);
        jScrollPane3.setViewportView(messagecont);

        showMessage.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 670, 254));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(48, 117, 233));
        jLabel5.setText("Message :");
        showMessage.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(48, 117, 233));
        jLabel6.setText("Subject :");
        showMessage.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(48, 117, 233));
        jLabel7.setText("From :");
        showMessage.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        fromLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        showMessage.add(fromLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 670, 20));

        subjectLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        showMessage.add(subjectLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 670, 20));

        jButton5.setBackground(new java.awt.Color(66, 133, 245));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Go Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        showMessage.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bluelogo.png"))); // NOI18N
        showMessage.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 55, 55));

        jPanelSlider1.add(showMessage, "card2");

        sendMessage.setBackground(new java.awt.Color(255, 255, 255));
        sendMessage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 133, 245), 10));
        sendMessage.setPreferredSize(new java.awt.Dimension(879, 462));
        sendMessage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sendCon.setColumns(20);
        sendCon.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        sendCon.setRows(5);
        jScrollPane2.setViewportView(sendCon);

        sendMessage.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 580, 260));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(48, 117, 233));
        jLabel2.setText("Subject :");
        sendMessage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(48, 117, 233));
        jLabel3.setText("To (ID):");
        sendMessage.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        sendSub.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        sendMessage.add(sendSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 580, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(48, 117, 233));
        jLabel4.setText("Message :");
        sendMessage.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        addMessage.setBackground(new java.awt.Color(66, 133, 245));
        addMessage.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        addMessage.setForeground(new java.awt.Color(255, 255, 255));
        addMessage.setText("Send");
        addMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMessageActionPerformed(evt);
            }
        });
        sendMessage.add(addMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 580, -1));

        jButton4.setBackground(new java.awt.Color(66, 133, 245));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Go Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        sendMessage.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        sendID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendIDActionPerformed(evt);
            }
        });
        sendMessage.add(sendID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 60, -1));
        sendMessage.add(showID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 120, 20));
        sendMessage.add(res, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 270, 20));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bluelogo.png"))); // NOI18N
        sendMessage.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 55, 55));

        jPanelSlider1.add(sendMessage, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void fillInfo(){ //gathering all set methods in one method
        
        svid.setText(""+infoPerson.getId());
        svname.setText(infoPerson.getName());
        svsname.setText(infoPerson.getSurname());
        svwplace.setText(infoStore.getCity());
        svstarting.setText(infoPerson.getStarting());
        svsalary.setText(""+infoPerson.getSalary());
        myEmployees=infoStore.getAllEmps();
        send=infoPerson.getAll();
        DefaultTableModel model1=(DefaultTableModel)jTable2.getModel();
        DefaultTableModel model2=(DefaultTableModel)jTable3.getModel();
        DefaultTableModel modelc=(DefaultTableModel)salarychange.getModel();
        //fireid.addItem("NONE");
        for(int i=0;i<myEmployees.size();i++){
        if(!(myEmployees.get(i).getId()==infoPerson.getId()))
            fireid.addItem(myEmployees.get(i).getId()+"");
        
            modelc.addRow(new Object[]{myEmployees.get(i).getId(),
                                       myEmployees.get(i).getName(),
                                       myEmployees.get(i).getSurname(),
                                       myEmployees.get(i).getSalary()});
            
            
            
           if(myEmployees.get(i).isOnVacation()){
               
                String date = myEmployees.get(i).getVacationTo();
                if(TimeDifference.isVacOver(date)){
                    myEmployees.get(i).updateOnVacation(false);
                    myEmployees.get(i).setOnVacation(false);
                }
                else{
                model2.addRow(new Object[]{myEmployees.get(i).getId(),
                                           myEmployees.get(i).getName(),
                                           myEmployees.get(i).getSurname(),
                                           myEmployees.get(i).getVacationTo()});
                }
            }
            if(!myEmployees.get(i).isOnVacation()){
                if(myEmployees.get(i).getId()==infoPerson.getId()){
                    model1.addRow(new Object[]{ myEmployees.get(i).getId(),
                                                myEmployees.get(i).getName()+"--(SV)",
                                                myEmployees.get(i).getSurname()});
                }else{
                    model1.addRow(new Object[]{ myEmployees.get(i).getId(),
                                                myEmployees.get(i).getName(),
                                                myEmployees.get(i).getSurname()});
                }
            }
        }
        all=refprod.getAll();
        for(int i=0;i<all.size();i++){
            if(all.get(i).getPlace()==infoStore.getStoreID()){
                myProducts.add(all.get(i));
            }           
        }
        infoStore.setProducts(myProducts);
        
        DefaultTableModel prodt=(DefaultTableModel)prodtable.getModel();
        for(int i=0;i<infoStore.getProducts().size();i++){   
            
             String bbfDate = infoStore.getProducts().get(i).getExpireDate();
            int keep = TimeDifference.isCloseBbf(bbfDate);
            
            if(infoStore.getProducts().get(i).getCategory().equalsIgnoreCase("other"))
            if(keep == 2){
                jLabel17.setVisible(true);
                bbfDate = "💀💀"+bbfDate;
            }
             else if(keep == 1)
                  bbfDate = "**"+bbfDate;
             if(infoStore.getProducts().get(i).getCategory().equalsIgnoreCase("other"))
                 bbfDate="--";
            prodt.addRow(new Object[]{infoStore.getProducts().get(i).getStockID(),
                                      infoStore.getProducts().get(i).getBrand(),
                                      infoStore.getProducts().get(i).getType(),
                                      infoStore.getProducts().get(i).getCost(),
                                      infoStore.getProducts().get(i).getPrice(),
                                      infoStore.getProducts().get(i).getCategory(),
                                      bbfDate,
                                      infoStore.getProducts().get(i).getStock()});
        }
        DefaultTableModel inb=(DefaultTableModel)svinbox.getModel();
        for(int i=0;i<messages.size();i++){
            Message control = messages.get(i);
            if(control.isChecked()){
                inb.addRow(new Object[]{
                ((Employee)infoPerson.get_item(messages.get(i).getFromID())).getName(),
                messages.get(i).getSubject()
                });      
            }
            else{
                inb.addRow(new Object[]{
                ("🔴"+((Employee)infoPerson.get_item(messages.get(i).getFromID())).getName()).toString(),
                messages.get(i).getSubject()
                });   
            }
        }
        prodbrand.setText("");
        prodtype.setText("");
        prodcost.setText("");
        prodprice.setText("");
        prodstock.setText("");
        proddate.setText("");
        
        for(int i=0;i<send.size();i++){
            if(infoPerson.getId()!=send.get(i).getId())
                sendID.addItem(send.get(i).getId()+"");
        }
        
    }
    
    private void setClear(){
        lineChart.id = infoPerson.getPlace();
        lineChart l = new lineChart(chart);
        DefaultTableModel clear1=(DefaultTableModel)jTable2.getModel();
        DefaultTableModel clear2=(DefaultTableModel)jTable3.getModel();
        DefaultTableModel clearc=(DefaultTableModel)salarychange.getModel();
        DefaultTableModel inb=(DefaultTableModel)svinbox.getModel();
        DefaultTableModel prodt=(DefaultTableModel)prodtable.getModel();
        clear1.setRowCount(0);
        clear2.setRowCount(0);
        clearc.setRowCount(0);
        inb.setRowCount(0);
        prodt.setRowCount(0);
        DefaultTableModel model1=(DefaultTableModel)jTable2.getModel();
        DefaultTableModel model2=(DefaultTableModel)jTable3.getModel();
        DefaultTableModel modelc=(DefaultTableModel)salarychange.getModel();
        //fireid.removeItemAt(fireid.getSelectedIndex());
        for(int i=0;i<myEmployees.size();i++){
            modelc.addRow(new Object[]{myEmployees.get(i).getId(),
                                       myEmployees.get(i).getName(),
                                       myEmployees.get(i).getSurname(),
                                       myEmployees.get(i).getSalary()});            
            if(!myEmployees.get(i).isOnVacation()){
            if(myEmployees.get(i).getId()==infoPerson.getId()){
                model1.addRow(new Object[]{ myEmployees.get(i).getId(),
                                            myEmployees.get(i).getName()+"--(SV)",
                                            myEmployees.get(i).getSurname()});
            }else{
                model1.addRow(new Object[]{ myEmployees.get(i).getId(),
                                            myEmployees.get(i).getName(),
                                            myEmployees.get(i).getSurname()});
            }
        }else{
            model2.addRow(new Object[]{myEmployees.get(i).getId(),
                                       myEmployees.get(i).getName(),
                                       myEmployees.get(i).getSurname(),
                                       myEmployees.get(i).getVacationTo()});
        }
        }
        
        for(int i=0;i<infoStore.getProducts().size();i++){
            
             String bbfDate = infoStore.getProducts().get(i).getExpireDate();
            int keep = TimeDifference.isCloseBbf(bbfDate);
            
 
            if(keep == 2){
                jLabel17.setVisible(true);
                bbfDate = "💀💀"+bbfDate;
            }
             else if(keep == 1)
                  bbfDate = "**"+bbfDate;
             if(infoStore.getProducts().get(i).getCategory().equalsIgnoreCase("other"))
                 bbfDate="--";
            
            
            prodt.addRow(new Object[]{infoStore.getProducts().get(i).getStockID(),
                                      infoStore.getProducts().get(i).getBrand(),
                                      infoStore.getProducts().get(i).getType(),
                                      infoStore.getProducts().get(i).getCost(),
                                      infoStore.getProducts().get(i).getPrice(),
                                      infoStore.getProducts().get(i).getCategory(),
                                      bbfDate,
                                      infoStore.getProducts().get(i).getStock()});
        }
        
        for(int i=0;i<messages.size();i++){
            Message control = messages.get(i);
            if(control.isChecked()){
                inb.addRow(new Object[]{
                ((Employee)infoPerson.get_item(messages.get(i).getFromID())).getName(),
                messages.get(i).getSubject()
                });      
            }
            else{
                inb.addRow(new Object[]{
                ("🔴"+((Employee)infoPerson.get_item(messages.get(i).getFromID())).getName()).toString(),
                messages.get(i).getSubject()
                });   
            }
    }
    }
    private void LogoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseEntered
        buttonEnter(LogoutButton);

    }//GEN-LAST:event_LogoutButtonMouseEntered

    private void LogoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseExited
        buttonExit(LogoutButton);
    }//GEN-LAST:event_LogoutButtonMouseExited

    private void LogoutButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMousePressed
        if(evt.getButton() == BUTTON1)
        buttonPress(LogoutButton);

    }//GEN-LAST:event_LogoutButtonMousePressed

    private void LogoutButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseReleased
        buttonRelease(LogoutButton);
        if(clicked && in){
            this.dispose();
            login p = new login();
            p.setVisible(true);
            clicked = false;
        }

    }//GEN-LAST:event_LogoutButtonMouseReleased

    private void rightButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightButtonMouseEntered
        if(rightButton.isEnabled())
        buttonEnter(rightButton);

    }//GEN-LAST:event_rightButtonMouseEntered

    private void rightButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightButtonMouseExited
        if(rightButton.isEnabled())
        buttonExit(rightButton);

    }//GEN-LAST:event_rightButtonMouseExited

    private void rightButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightButtonMousePressed
        if(evt.getButton() == BUTTON1 && rightButton.isEnabled())
        buttonPress(rightButton);

    }//GEN-LAST:event_rightButtonMousePressed

    private void rightButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightButtonMouseReleased
        if(rightButton.isEnabled())
        buttonRelease(rightButton);

        if(in){
            if(clicked && info_bool){
                jPanelSlider1.nextPanel(10,workerList, jPanelSlider1.right);
                pos_worker.setForeground(new Color(255,204,51));
                pos_info.setForeground(Color.white);
                worker_bool = true;
                info_bool=false;
            }
            else if(clicked && worker_bool){
                jPanelSlider1.nextPanel(10,stock, jPanelSlider1.right);
                pos_stock.setForeground(new Color(255,204,51));
                pos_worker.setForeground(Color.white);
                stock_bool = true;
                worker_bool=false;
            }
            else if(clicked && stock_bool){
                jPanelSlider1.nextPanel(10,chart, jPanelSlider1.right);
                pos_chart.setForeground(new Color(255,204,51));
                pos_stock.setForeground(Color.white);
                chart_bool = true;
                stock_bool=false;

            }
            else if(clicked && chart_bool){
                jPanelSlider1.nextPanel(10,inbox, jPanelSlider1.right);
                pos_inbox.setForeground(new Color(255,204,51));
                pos_chart.setForeground(Color.white);
                inbox_bool = true;
                chart_bool=false;

            }
            else if(clicked && inbox_bool){
                jPanelSlider1.nextPanel(10,info, jPanelSlider1.right);
                pos_info.setForeground(new Color(255,204,51));
                pos_inbox.setForeground(Color.white);
                info_bool = true;
                inbox_bool=false;

            }

        }

        clicked = false;

    }//GEN-LAST:event_rightButtonMouseReleased

    private void prodBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodBuyActionPerformed
        rightButton.setEnabled(false);
        jPanelSlider1.nextPanel(10, addProduct, jPanelSlider1.left);
    }//GEN-LAST:event_prodBuyActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         rightButton.setEnabled(true);
        jPanelSlider1.nextPanel(10, stock, jPanelSlider1.right);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void showMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMesActionPerformed
       try{
            rightButton.setEnabled(false);
            fromLabel.setText(svinbox.getValueAt(svinbox.getSelectedRow(), 0).toString());
            subjectLabel.setText(svinbox.getValueAt(svinbox.getSelectedRow(), 1).toString());
            jPanelSlider1.nextPanel(10, showMessage , jPanelSlider1.left);}
        catch(ArrayIndexOutOfBoundsException e){

            JOptionPane.showMessageDialog(jDialog1,
                "You have to select a row to see a message",
                "Error",
                JOptionPane.WARNING_MESSAGE);

        }
       
        Message find = messages.get(svinbox.getSelectedRow());
        if(find != null){
            find.updateCheck();
            messagecont.setText(messages.get(svinbox.getSelectedRow()).getContext());
            setClear();
        }
        
          
    }//GEN-LAST:event_showMesActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        rightButton.setEnabled(true);
        jPanelSlider1.nextPanel(10, inbox, jPanelSlider1.right);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        rightButton.setEnabled(true);
        jPanelSlider1.nextPanel(10, inbox, jPanelSlider1.right);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void sendMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMesActionPerformed
        rightButton.setEnabled(false);
        jPanelSlider1.nextPanel(10, sendMessage, jPanelSlider1.left);
        /*send=infoPerson.getAll();
        for(int i=0;i<send.size();i++){
            if(infoPerson.getId()!=send.get(i).getId())
                sendID.addItem(send.get(i).getId()+"");
        }*/
    }//GEN-LAST:event_sendMesActionPerformed

    private void fireidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireidActionPerformed
        if(!fireid.getSelectedItem().toString().equalsIgnoreCase("none") && !fireid.getSelectedItem().equals(null) && !fireid.getSelectedItem().toString().equals("")){
            firePerson=(Employee)infoPerson.get_item(Integer.parseInt(fireid.getSelectedItem().toString()));
            firename.setText(firePerson.getName());
            firesurname.setText(firePerson.getSurname());
            firecompens.setText(""+firePerson.getSalary());
           
        }else{
            firename.setText("");
            firesurname.setText("");
            firecompens.setText("");
        }

    }//GEN-LAST:event_fireidActionPerformed

    private void firebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firebuttonActionPerformed
        if(!fireid.getSelectedItem().toString().equalsIgnoreCase("none")){
            myEmployees=infoPerson.delete_item(myEmployees, Integer.parseInt(fireid.getSelectedItem().toString()));
            fireid.removeItemAt(fireid.getSelectedIndex());
            setClear();
            //fireid.setSelectedIndex(0);
        }
    }//GEN-LAST:event_firebuttonActionPerformed

    private void addbuttonwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonwActionPerformed
        
        if(addwname.getText()!=""&&addwsurname.getText()!=""&&addwsalary.getText()!=""){
            Employee add=new Employee(addwname.getText(),addwsurname.getText(),infoPerson.getPlace());
            add.setSalary(Integer.parseInt(addwsalary.getText()));
            add.setStatus("WORKER");
            add.add_item(add);
            this.myEmployees=infoStore.getAllEmps();
            fireid.addItem((add.getId())+"");
            jLabel39.setVisible(true);
            setClear();            
        }
    }//GEN-LAST:event_addbuttonwActionPerformed

    private void csalarybActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csalarybActionPerformed
        Employee cs=(Employee)infoPerson.get_item(Integer.parseInt(salarychange.getValueAt(salarychange.getSelectedRow(), 0).toString()));
        for(int i=0;i<myEmployees.size();i++){
            if(myEmployees.get(i).getId()==cs.getId()){
                if(myEmployees.get(i).updateSalary(Double.parseDouble(csalary.getText()))){
                    dispcs.setText("SUCCESS!!");
                    setClear();
                    svsalary.setText(myEmployees.get(i).getSalary()+"");
                }
            }
        }
    }//GEN-LAST:event_csalarybActionPerformed

    private void sendIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendIDActionPerformed
        showID.setText(((Employee)infoPerson.get_item(Integer.parseInt(sendID.getSelectedItem().toString()))).getName()+"  "+((Employee)infoPerson.get_item(Integer.parseInt(sendID.getSelectedItem().toString()))).getSurname());
    }//GEN-LAST:event_sendIDActionPerformed

    private void addMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMessageActionPerformed
        if((sendSub.getText()!="" || sendSub.getText()!=null)&&(sendCon.getText()!="" || sendCon.getText()!=null)){
            sen=new Message(infoPerson.getId(),Integer.parseInt(sendID.getSelectedItem().toString()),sendSub.getText(),sendCon.getText());
            ref.add_item(sen);
            res.setText("Succesfull!");
            sendSub.setText("");
            sendCon.setText("");
        }else{
            res.setText("Context and subject cannot be empty!");
        }
    }//GEN-LAST:event_addMessageActionPerformed

    private void prodcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodcostActionPerformed

    private void prodpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodpriceActionPerformed

    private void prodcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodcatActionPerformed
        if(prodcat.getSelectedIndex()==1){
            proddate.setVisible(false);
            prodd1.setVisible(false);
            prodd2.setVisible(false);
        }else{
            proddate.setVisible(true);
            prodd1.setVisible(true);
            prodd2.setVisible(true);
        }
    }//GEN-LAST:event_prodcatActionPerformed

    private void prodaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodaddActionPerformed
        if(prodbrand.getText()!=""&&prodtype.getText()!=""&&prodcost.getText()!=""&&prodprice.getText()!=""&&prodstock.getText()!=""){
            if(prodcat.getSelectedIndex()==1){
                ad=new Product(prodbrand.getText(),prodtype.getText(),Double.parseDouble(prodcost.getText()),Double.parseDouble(prodprice.getText()),Integer.parseInt(prodstock.getText()),infoPerson.getPlace(),prodcat.getSelectedItem().toString(),"2050-12-12");
            }else{
                ad=new Product(prodbrand.getText(),prodtype.getText(),Double.parseDouble(prodcost.getText()),Double.parseDouble(prodprice.getText()),Integer.parseInt(prodstock.getText()),infoPerson.getPlace(),prodcat.getSelectedItem().toString(),proddate.getText());
            }
            if(refprod.add_item(ad)){
                prodres.setText("Success!");
                prodbrand.setText("");
                prodtype.setText("");
                prodcost.setText("");
                prodprice.setText("");
                prodstock.setText("");
                proddate.setText("");
                myProducts.clear();
            }
        }else{
            prodres.setText("All Fields Must Be Filled!");
        }
        all=refprod.getAll();        
        for(int i=0;i<all.size();i++){
            if(infoStore.getStoreID()==all.get(i).getPlace()){
                myProducts.add(all.get(i));
            }
        }
        infoStore.setProducts(myProducts);
        setClear();
             

    }//GEN-LAST:event_prodaddActionPerformed

    private void proddateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proddateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proddateActionPerformed

    private void prodSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodSellActionPerformed
        DefaultTableModel sell=(DefaultTableModel)prodtable.getModel();
        Product calc = Product.findProduct(infoStore.getProducts(), Integer.parseInt(sell.getValueAt(prodtable.getSelectedRow(), 0).toString()));
        infoStore.setProducts(refprod.delete_item(infoStore.getProducts(), Integer.parseInt(sell.getValueAt(prodtable.getSelectedRow(), 0).toString())));
        myProducts=infoStore.getProducts();
        double[] arr = infoStore.getEndor();
        arr[LocalDate.now().getDayOfMonth()-1] = calc.getPrice()*calc.getStock();
        infoStore.updateEndor(arr);
        setClear();
    }//GEN-LAST:event_prodSellActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoutButton;
    private javax.swing.JButton addMessage;
    private javax.swing.JPanel addProduct;
    private javax.swing.JPanel addWorker;
    private javax.swing.JButton addbuttonw;
    private javax.swing.JTextField addwname;
    private javax.swing.JTextField addwsalary;
    private javax.swing.JTextField addwsurname;
    private javax.swing.JPanel chart;
    private javax.swing.JTextField csalary;
    private javax.swing.JButton csalaryb;
    private javax.swing.JPanel deleteWorker;
    private javax.swing.JLabel dispResult;
    private javax.swing.JLabel dispcs;
    private javax.swing.JButton firebutton;
    private javax.swing.JLabel firecompens;
    private javax.swing.JComboBox<String> fireid;
    private javax.swing.JLabel firename;
    private javax.swing.JLabel firesurname;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JPanel inbox;
    private javax.swing.JPanel info;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private diu.swe.habib.JPanelSlider.JPanelSlider jPanelSlider1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea messagecont;
    private javax.swing.JLabel pos_chart;
    private javax.swing.JLabel pos_inbox;
    private javax.swing.JLabel pos_info;
    private javax.swing.JLabel pos_stock;
    private javax.swing.JLabel pos_worker;
    private javax.swing.JButton prodBuy;
    private javax.swing.JButton prodSell;
    private javax.swing.JButton prodadd;
    private javax.swing.JTextField prodbrand;
    private javax.swing.JComboBox<String> prodcat;
    private javax.swing.JTextField prodcost;
    private javax.swing.JLabel prodd1;
    private javax.swing.JLabel prodd2;
    private javax.swing.JTextField proddate;
    private javax.swing.JTextField prodprice;
    private javax.swing.JLabel prodres;
    private javax.swing.JTextField prodstock;
    private javax.swing.JTable prodtable;
    private javax.swing.JTextField prodtype;
    private javax.swing.JLabel res;
    private javax.swing.JLabel rightButton;
    private javax.swing.JTable salarychange;
    private javax.swing.JTextArea sendCon;
    private javax.swing.JComboBox<String> sendID;
    private javax.swing.JButton sendMes;
    private javax.swing.JPanel sendMessage;
    private javax.swing.JTextField sendSub;
    private javax.swing.JLabel showID;
    private javax.swing.JButton showMes;
    private javax.swing.JPanel showMessage;
    private javax.swing.JPanel stock;
    private javax.swing.JLabel subjectLabel;
    private javax.swing.JLabel svid;
    private javax.swing.JTable svinbox;
    private javax.swing.JLabel svname;
    private javax.swing.JLabel svsalary;
    private javax.swing.JLabel svsname;
    private javax.swing.JLabel svstarting;
    private javax.swing.JLabel svwplace;
    private javax.swing.JPanel workerList;
    // End of variables declaration//GEN-END:variables
 void buttonExit(Component c){
         timer1.cancel();
        timer3.cancel();

       
            
            TimerTask task1 = new TimerTask() {
                @Override
                public void run() {
                    if (c.getBackground().getRed() >= 48) {

                    c.setBackground(new Color(c.getBackground().getRed()-1,c.getBackground().getGreen()-1,c.getBackground().getBlue()));
                }
                else if(c.getBackground().getRed() < 48){
                    c.setBackground(new Color(c.getBackground().getRed()+1,c.getBackground().getGreen()+1,c.getBackground().getBlue()));
                }
                }
            };
            in = false;
            timer2 = new Timer();
            timer2.scheduleAtFixedRate(task1, 0, 20);
        
        
    }
    void buttonEnter(Component c){
         timer3.cancel();
        timer2.cancel();

        
            
            TimerTask task1 = new TimerTask() {
                @Override
                public void run() {
                     if (c.getBackground().getRed() <= 60) {

                    c.setBackground(new Color(c.getBackground().getRed()+1,c.getBackground().getGreen()+1,c.getBackground().getBlue()));
                }
                }
            };
            in = true;
            timer1 = new Timer();
            timer1.scheduleAtFixedRate(task1, 0, 20);
        
        
    }
    void buttonPress(Component c){
        timer1.cancel();
        timer2.cancel();

       
            clicked = true;
            TimerTask task1 = new TimerTask() {
                @Override
                public void run() {
                    if (c.getBackground().getRed() >= 28) {

                        c.setBackground(new Color(c.getBackground().getRed()-1,c.getBackground().getGreen()-1,c.getBackground().getBlue()));
                    }
                }
            };

            timer3 = new Timer();
            timer3.scheduleAtFixedRate(task1, 0, 20);
        
    }
    void buttonRelease(Component c){
        if(in){
            timer2.cancel();
            timer3.cancel();
            TimerTask task1 = new TimerTask() {
                @Override
                public void run() {
                    if (c.getBackground().getRed() <= 60) {

                        c.setBackground(new Color(c.getBackground().getRed()+1,c.getBackground().getGreen()+1,c.getBackground().getBlue()));
                    }
                }
            };
            timer1 = new Timer();
            timer1.scheduleAtFixedRate(task1, 0, 20);
        
    }
    }
    
}
