package GUI;



import GUI.login;
import chainmanagement.Employee;
import chainmanagement.Message;
import chainmanagement.Store;
import chainmanagement.TimeDifference;
import java.awt.Color;
import java.awt.Component;
import java.awt.Label;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import static java.awt.event.MouseEvent.BUTTON1;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;

import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

import org.jdesktop.swingx.border.DropShadowBorder;
import org.jfree.data.gantt.Task;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACK
 */
public class workerPanel extends javax.swing.JFrame {

    /**
     * Creates new form Panel2
     */
    Timer check=new Timer();
    public static int vac = 3;
    Timer timer1 = new Timer();
    Timer timer2 = new Timer();
    Timer timer3 = new Timer();
    Timer slideTimer1 = new Timer();
    Timer slideTimer2 = new Timer();
    Employee infoPerson;
    Store ref = new Store();
    ArrayList<Message> messages=new ArrayList<>(); 
      
      boolean in;
      boolean clicked;
      
      boolean new_message;
      boolean v_bool;
      boolean i_bool;
      boolean info_bool = true;
    
 
    
      
      
      
    public workerPanel(Employee e) {
        
        infoPerson=e;
        initComponents();
        
        jPanel2.setLayer(jPanel3, 2);
        
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        
        
        setBackground(new Color(0,0,0,0));
        jPanel2.setBackground(new Color(0,0,0,0));
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShadowColor(Color.BLACK);
        shadow.setShowLeftShadow(true);
        shadow.setShowRightShadow(true);
        shadow.setShowBottomShadow(true);
        shadow.setShowTopShadow(true);
        shadow.setShadowSize(6);
        jPanel2.setBorder(shadow);
        jLabel7.setVisible(false);
        
        
        
        
        if(new_message)
            jLabel7.setVisible(true);
            fillInfo();
        
        /*check.scheduleAtFixedRate(new TimerTask(){
            @Override
            public void run(){
                fillInfo();
            }
        }, 1000*60, 1000*60);*/
        
    }    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JLayeredPane();
        jPanel3 = new javax.swing.JPanel();
        LogoutButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pos_info = new javax.swing.JLabel();
        rightButton = new javax.swing.JLabel();
        pos_inbox = new javax.swing.JLabel();
        pos_vacation = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanelSlider1 = new diu.swe.habib.JPanelSlider.JPanelSlider();
        info = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lab_ID = new javax.swing.JLabel();
        lab_name = new javax.swing.JLabel();
        lab_surname = new javax.swing.JLabel();
        lab_branch = new javax.swing.JLabel();
        lab_start = new javax.swing.JLabel();
        lab_salary = new javax.swing.JLabel();
        inbox = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        message = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();
        messageFrom = new javax.swing.JLabel();
        messageSubject = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        vacation = new javax.swing.JPanel();
        dateFrom = new com.toedter.calendar.JDateChooser();
        dateTo = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        vacResult = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(66, 133, 245));

        LogoutButton.setBackground(new java.awt.Color(48, 117, 233));
        LogoutButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoutButton.setText("Logout");
        LogoutButton.setOpaque(true);
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogoutButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Chain Marketing Management System Worker Panel");

        pos_info.setBackground(new java.awt.Color(255, 255, 255));
        pos_info.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pos_info.setForeground(new java.awt.Color(255, 204, 51));
        pos_info.setText("Info");

        rightButton.setBackground(new java.awt.Color(48, 117, 233));
        rightButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rightButton.setForeground(new java.awt.Color(255, 255, 255));
        rightButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/right_arrow.png"))); // NOI18N
        rightButton.setOpaque(true);
        rightButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rightButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rightButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rightButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rightButtonMouseReleased(evt);
            }
        });

        pos_inbox.setBackground(new java.awt.Color(255, 255, 255));
        pos_inbox.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pos_inbox.setForeground(new java.awt.Color(255, 255, 255));
        pos_inbox.setText("Inbox");

        pos_vacation.setBackground(new java.awt.Color(255, 255, 255));
        pos_vacation.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pos_vacation.setForeground(new java.awt.Color(255, 255, 255));
        pos_vacation.setText("Vacation");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/warning.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rightButton)
                        .addGap(313, 313, 313)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(pos_inbox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addComponent(pos_info)
                            .addComponent(pos_vacation))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(pos_info, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(pos_inbox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pos_vacation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(rightButton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanelSlider1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSlider1.setBorder(null);

        info.setBackground(new java.awt.Color(255, 255, 255));
        info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 133, 245), 10));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/img_464447.png"))); // NOI18N
        jLabel8.setText("Photo");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(48, 117, 233));
        jLabel9.setText("ID :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(48, 117, 233));
        jLabel10.setText("Name :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(48, 117, 233));
        jLabel11.setText("Work period :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(48, 117, 233));
        jLabel12.setText("Salary :");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(48, 117, 233));
        jLabel18.setText("Branch :");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(48, 117, 233));
        jLabel19.setText("Surname :");

        lab_ID.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lab_ID.setText("jLabel2");

        lab_name.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lab_name.setText("jLabel3");

        lab_surname.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lab_surname.setText("jLabel4");

        lab_branch.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lab_branch.setText("jLabel5");

        lab_start.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lab_start.setText("jLabel6");

        lab_salary.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lab_salary.setText("jLabel20");

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(34, 34, 34)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lab_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_start, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_branch, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lab_name, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(521, Short.MAX_VALUE))
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoLayout.createSequentialGroup()
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lab_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lab_name, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(lab_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(lab_branch, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lab_start, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lab_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSlider1.add(info, "card3");

        inbox.setBackground(new java.awt.Color(255, 255, 255));
        inbox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 133, 245), 10));
        inbox.setPreferredSize(new java.awt.Dimension(879, 264));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "From", "Subject"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jButton1.setText("Show Message");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inboxLayout = new javax.swing.GroupLayout(inbox);
        inbox.setLayout(inboxLayout);
        inboxLayout.setHorizontalGroup(
            inboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        inboxLayout.setVerticalGroup(
            inboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inboxLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
        );

        jPanelSlider1.add(inbox, "card2");

        message.setBackground(new java.awt.Color(255, 255, 255));
        message.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 133, 245), 10));

        jLabel13.setText("From :");

        jLabel14.setText("Subject :");

        jLabel15.setText("Message :");

        messageArea.setColumns(20);
        messageArea.setRows(5);
        jScrollPane2.setViewportView(messageArea);

        jButton2.setBackground(new java.awt.Color(48, 117, 233));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back to Inbox");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout messageLayout = new javax.swing.GroupLayout(message);
        message.setLayout(messageLayout);
        messageLayout.setHorizontalGroup(
            messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageLayout.createSequentialGroup()
                .addGroup(messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(messageLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(messageLayout.createSequentialGroup()
                                .addGroup(messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(messageFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(messageSubject, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(messageLayout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(jLabel15)))
                .addGap(0, 116, Short.MAX_VALUE))
        );
        messageLayout.setVerticalGroup(
            messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageLayout.createSequentialGroup()
                .addGap(0, 32, Short.MAX_VALUE)
                .addGroup(messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(messageFrom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jButton2))
                .addGap(28, 28, 28)
                .addGroup(messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(messageSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelSlider1.add(message, "card4");

        vacation.setBackground(new java.awt.Color(255, 255, 255));
        vacation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 133, 245), 10));

        dateFrom.setBackground(new java.awt.Color(48, 117, 233));
        dateFrom.setForeground(new java.awt.Color(48, 117, 233));

        dateTo.setBackground(new java.awt.Color(48, 117, 233));
        dateTo.setForeground(new java.awt.Color(48, 117, 233));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(48, 117, 233));
        jLabel16.setText("From :");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(48, 117, 233));
        jLabel17.setText("To :");

        vacResult.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vacResult.setForeground(new java.awt.Color(48, 117, 233));

        submitButton.setBackground(new java.awt.Color(48, 117, 233));
        submitButton.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vacationLayout = new javax.swing.GroupLayout(vacation);
        vacation.setLayout(vacationLayout);
        vacationLayout.setHorizontalGroup(
            vacationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vacationLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(vacationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(vacationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateFrom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                .addGroup(vacationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vacResult, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        vacationLayout.setVerticalGroup(
            vacationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vacationLayout.createSequentialGroup()
                .addGroup(vacationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vacationLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(vacationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vacResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(dateFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(vacationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vacationLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jPanelSlider1.add(vacation, "card4");

        jPanel2.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanel2.setLayer(jPanelSlider1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void fillInfo(){
        lab_ID.setText(""+infoPerson.getId());
        lab_name.setText(infoPerson.getName());
        lab_surname.setText(infoPerson.getSurname());
        Store place=(Store)ref.get_item(infoPerson.getPlace());
        if(place == null)
            lab_branch.setText("Not found");
        else
            lab_branch.setText(place.getCity());
        lab_start.setText(infoPerson.getStarting());
        lab_salary.setText(""+infoPerson.getSalary());
        DefaultTableModel a=(DefaultTableModel)jTable1.getModel();
        Employee refMes;
        messages=Message.getAll_Messages(infoPerson.getId());
        for(int i=0;i<messages.size();i++){
            
            refMes=(Employee)infoPerson.get_item(messages.get(i).getFromID());
            String date = refMes.getVacationTo();
            if(messages.get(i).isChecked()){
                a.addRow(new Object[]{  refMes.getName(),
                messages.get(i).getSubject()});
                
            }
            else{
                a.addRow(new Object[]{  "🔴"+refMes.getName(),
                messages.get(i).getSubject()});    
                jLabel7.setVisible(true);
        }
    }
    }
    
    void setClear(){
        DefaultTableModel a=(DefaultTableModel)jTable1.getModel();
        Employee refMes;
        a.setNumRows(0);
        messages=Message.getAll_Messages(infoPerson.getId());
        for(int i=0;i<messages.size();i++){
            
            refMes=(Employee)infoPerson.get_item(messages.get(i).getFromID());
            String date = refMes.getVacationTo();
            if(messages.get(i).isChecked()){
                a.addRow(new Object[]{  refMes.getName(),
                messages.get(i).getSubject()});
                
            }
            else{
                a.addRow(new Object[]{  "🔴"+refMes.getName(),
                messages.get(i).getSubject()});    
                jLabel7.setVisible(true);
        }
    }}
    private void LogoutButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseReleased
            buttonRelease(LogoutButton);
            if(clicked && in){
                this.dispose();
                login p = new login();
                p.setVisible(true);
                clicked = false;
            }
                
        
    }//GEN-LAST:event_LogoutButtonMouseReleased

    private void LogoutButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMousePressed
        if(evt.getButton() == BUTTON1)
         buttonPress(LogoutButton);
        
    }//GEN-LAST:event_LogoutButtonMousePressed

    private void LogoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseExited
     buttonExit(LogoutButton);
    }//GEN-LAST:event_LogoutButtonMouseExited

    private void LogoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseEntered
        buttonEnter(LogoutButton);
       
    }//GEN-LAST:event_LogoutButtonMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        rightButton.setEnabled(false);
        messageFrom.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        //messageSubject.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        jPanelSlider1.nextPanel(10,message, jPanelSlider1.left);
        messageArea.setText(messages.get(jTable1.getSelectedRow()).getContext());
        messages.get(jTable1.getSelectedRow()).updateCheck();
        messageSubject.setText(messages.get(jTable1.getSelectedRow()).getSubject());
        jLabel7.setVisible(false);
        setClear();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        rightButton.setEnabled(true);
        jPanelSlider1.nextPanel(10,inbox, jPanelSlider1.right);
        messageArea.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rightButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightButtonMouseReleased
        if(rightButton.isEnabled())
        buttonRelease(rightButton);

            if(in){
                if(clicked && info_bool){
                jPanelSlider1.nextPanel(10,inbox, jPanelSlider1.right);
                pos_inbox.setForeground(new Color(255,204,51));
                pos_info.setForeground(Color.white);
                i_bool = true;
                info_bool=false;
            }
            else if(clicked && i_bool){
                jPanelSlider1.nextPanel(10,vacation, jPanelSlider1.right);
                pos_vacation.setForeground(new Color(255,204,51));
                pos_inbox.setForeground(Color.white);
                v_bool = true;
                i_bool=false;
            }
            else if(clicked && v_bool){
                jPanelSlider1.nextPanel(10,info, jPanelSlider1.right);
                pos_info.setForeground(new Color(255,204,51));
                pos_vacation.setForeground(Color.white);
                info_bool = true;
                v_bool=false;

            }

            }
            
            clicked = false;

        
    }//GEN-LAST:event_rightButtonMouseReleased

    private void rightButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightButtonMousePressed
         if(evt.getButton() == BUTTON1 && rightButton.isEnabled())
        buttonPress(rightButton);
   
        
    }//GEN-LAST:event_rightButtonMousePressed

    private void rightButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightButtonMouseExited
        if(rightButton.isEnabled())
        buttonExit(rightButton);
        
    }//GEN-LAST:event_rightButtonMouseExited

    private void rightButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightButtonMouseEntered
        if(rightButton.isEnabled())
        buttonEnter(rightButton);
        
    }//GEN-LAST:event_rightButtonMouseEntered

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
         Calendar from;
        Calendar to;
        Message send = new Message();
        Calendar current=Calendar.getInstance();
        try{
            SimpleDateFormat formatter=new SimpleDateFormat("yyyy-MM-dd");
            Date cr=Calendar.getInstance().getTime();
            current.setTime(cr);
            from=dateFrom.getCalendar();
            LocalDate a = LocalDate.now();
            to=dateTo.getCalendar();
            Date dateto=dateTo.getDate();
            
            if(current.compareTo(from)<0 && from.compareTo(to)<0 && !infoPerson.isOnVacation()){
                int between=(int)Duration.between(from.toInstant(), to.toInstant()).toDays();
                if(infoPerson.getPermit()>between){
                    infoPerson.updatePermit(infoPerson.getPermit()-between);
                    infoPerson.updateOnVacation(true);
                    infoPerson.updateVacationTo(formatter.format(dateto));
                    vacResult.setText("You took "+between+" days of vacation!"+formatter.format(dateto));
                    String inform = infoPerson.getName()+" "+infoPerson.getSurname()+"("+infoPerson.getId()+") WENT ON VACATION";
                    send.add_item(new Message(infoPerson.getId(), infoPerson.getSupervisorID(), "SYSTEM NOTIFICATION", inform));
                }else{
                    vacResult.setText("You dont have enough permits");
                }
                
            }else{
                vacResult.setText("Invalid values");
            }
           
        }
        
        catch(NullPointerException e){
            vacResult.setText("Date selection shouldn't be empty");
        }
    }//GEN-LAST:event_submitButtonActionPerformed
    void buttonExit(Component c){
         timer1.cancel();
        timer3.cancel();

       
            
            TimerTask task1 = new TimerTask() {
                @Override
                public void run() {
                    if (c.getBackground().getRed() >= 48) {

                    c.setBackground(new Color(c.getBackground().getRed()-1,c.getBackground().getGreen()-1,c.getBackground().getBlue()));
                }
                else if(c.getBackground().getRed() < 48){
                    c.setBackground(new Color(c.getBackground().getRed()+1,c.getBackground().getGreen()+1,c.getBackground().getBlue()));
                }
                }
            };
            in = false;
            timer2 = new Timer();
            timer2.scheduleAtFixedRate(task1, 0, 20);
        
        
    }
    void buttonEnter(Component c){
         timer3.cancel();
        timer2.cancel();

        
            
            TimerTask task1 = new TimerTask() {
                @Override
                public void run() {
                     if (c.getBackground().getRed() <= 60) {

                    c.setBackground(new Color(c.getBackground().getRed()+1,c.getBackground().getGreen()+1,c.getBackground().getBlue()));
                }
                }
            };
            in = true;
            timer1 = new Timer();
            timer1.scheduleAtFixedRate(task1, 0, 20);
        
        
    }
    void buttonPress(Component c){
        timer1.cancel();
        timer2.cancel();

       
            clicked = true;
            TimerTask task1 = new TimerTask() {
                @Override
                public void run() {
                    if (c.getBackground().getRed() >= 28) {

                        c.setBackground(new Color(c.getBackground().getRed()-1,c.getBackground().getGreen()-1,c.getBackground().getBlue()));
                    }
                }
            };

            timer3 = new Timer();
            timer3.scheduleAtFixedRate(task1, 0, 20);
        
    }
    void buttonRelease(Component c){
        if(in){
            timer2.cancel();
            timer3.cancel();
            TimerTask task1 = new TimerTask() {
                @Override
                public void run() {
                    if (c.getBackground().getRed() <= 60) {

                        c.setBackground(new Color(c.getBackground().getRed()+1,c.getBackground().getGreen()+1,c.getBackground().getBlue()));
                    }
                }
            };
            timer1 = new Timer();
            timer1.scheduleAtFixedRate(task1, 0, 20);
        
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoutButton;
    private com.toedter.calendar.JDateChooser dateFrom;
    private com.toedter.calendar.JDateChooser dateTo;
    private javax.swing.JPanel inbox;
    private javax.swing.JPanel info;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jPanel2;
    private javax.swing.JPanel jPanel3;
    private diu.swe.habib.JPanelSlider.JPanelSlider jPanelSlider1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lab_ID;
    private javax.swing.JLabel lab_branch;
    private javax.swing.JLabel lab_name;
    private javax.swing.JLabel lab_salary;
    private javax.swing.JLabel lab_start;
    private javax.swing.JLabel lab_surname;
    private javax.swing.JPanel message;
    private javax.swing.JTextArea messageArea;
    private javax.swing.JLabel messageFrom;
    private javax.swing.JLabel messageSubject;
    private javax.swing.JLabel pos_inbox;
    private javax.swing.JLabel pos_info;
    private javax.swing.JLabel pos_vacation;
    private javax.swing.JLabel rightButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel vacResult;
    private javax.swing.JPanel vacation;
    // End of variables declaration//GEN-END:variables
}
